// Mocks generated by Mockito 5.4.5 from annotations
// in flora_mart/test/data/repo_impl/guest_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flora_mart/data/datasource_contract/guest_datasource.dart'
    as _i2;
import 'package:flora_mart/domain/common/result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GuestDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuestDatasource extends _i1.Mock implements _i2.GuestDatasource {
  MockGuestDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<bool>> checkGuest() =>
      (super.noSuchMethod(
            Invocation.method(#checkGuest, []),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i5.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#checkGuest, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<bool> changeGuest({required bool? isGuest}) =>
      (super.noSuchMethod(
            Invocation.method(#changeGuest, [], {#isGuest: isGuest}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
