// Mocks generated by Mockito 5.4.5 from annotations
// in flora_mart/test/presentation/auth/view_model/cubit/auth_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flora_mart/domain/common/result.dart' as _i5;
import 'package:flora_mart/domain/repo_contract/guest_repo.dart' as _i2;
import 'package:flora_mart/domain/usecase/changeGuest_usecase.dart' as _i7;
import 'package:flora_mart/domain/usecase/check_guest_usecase.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGuestRepo_0 extends _i1.SmartFake implements _i2.GuestRepo {
  _FakeGuestRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckGuestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckGuestUseCase extends _i1.Mock implements _i3.CheckGuestUseCase {
  MockCheckGuestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GuestRepo get authRepo =>
      (super.noSuchMethod(
            Invocation.getter(#authRepo),
            returnValue: _FakeGuestRepo_0(this, Invocation.getter(#authRepo)),
          )
          as _i2.GuestRepo);

  @override
  _i4.Future<_i5.Result<bool>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<bool>>.value(
              _i6.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool>>);
}

/// A class which mocks [ChangeguestUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangeguestUsecase extends _i1.Mock
    implements _i7.ChangeguestUsecase {
  MockChangeguestUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GuestRepo get authRepo =>
      (super.noSuchMethod(
            Invocation.getter(#authRepo),
            returnValue: _FakeGuestRepo_0(this, Invocation.getter(#authRepo)),
          )
          as _i2.GuestRepo);

  @override
  _i4.Future<bool> call({required bool? isGuest}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#isGuest: isGuest}),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
